spring:
  application:
    name: AIGymTracker

  datasource:
    url: jdbc:mysql://localhost:3306/health_tracker_db?createDatabaseIfNotExist=true
    username: root
    password: andi1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jwt:
    secret: "D62Z3JZYjEl2rf1J5vuIMfqOhxULGfaGCP8V2TuzHlo="
    accessTokenExpiration: 9000000
    refreshTokenExpiration: 604800
